trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  DATABRICKS_HOST: 'https://adb-2340809536712597.17.azuredatabricks.net/?o=2340809536712597' 
  DATABRICKS_TOKEN: 'dapi1d826d409db7ed1b9669c8bec93e9a4e'          
  MODEL_NAME: 'arima_demand_forecast'
  MODEL_VERSION: '1'
  STAGE: 'Production'

jobs:
- job: PromoteModel
  steps:
  - script: |
      curl -X POST "$DATABRICKS_HOST/api/2.0/mlflow/model-versions/transition-stage" \
        -H "Authorization: Bearer $DATABRICKS_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
              "name": "'$MODEL_NAME'",
              "version": "'$MODEL_VERSION'",
              "stage": "'$STAGE'",
              "archive_existing_versions": false
            }'
    displayName: 'Promote Model to Production'
